#!/bin/bash
rm -rf /etc/localtime; ln -s /usr/share/zoneinfo/America/Santo_Domingo /etc/localtime; 
yum remove -y selinux-policy-targeted; service auditd stop; chkconfig auditd off; 
yum groupinstall "Developent Tools" -y; yum install -y nano wget zip unzip screen perl epel-release psmisc mlocate; 
wget repo.sysdop.com/resolv.conf;/usr/bin/mv -f /tmp/resolv.conf /etc/resolv.conf;chattr +a +i /etc/resolv.conf;yum remove firewall* firewalld* -y; 
wget repo.sysdop.com/config.selinux -O /etc/selinux/config; chattr +a +i /etc/selinux/config; 
yum autoremove -y; yum upgrade -y --skip-broken; 
yum install ntp ntpdate sqlite* -y; 
chkconfig ntpd on; service ntpd restart; ntpdate pool.ntp.org;
yum install -y https://mirror.city-fan.org/ftp/contrib/yum-repo/city-fan.org-release-2-1.rhel7.noarch.rpm; 
yum install -y https://centos7.iuscommunity.org/ius-release.rpm; 
yum install -y http://li.nux.ro/download/nux/dextop/el7/x86_64/nux-dextop-release-0-5.el7.nux.noarch.rpm; 
yum install -y http://rpms.famillecollet.com/enterprise/remi-release-7.rpm; 
yum upgrade -y --skip-broken; 
wget repo.sysdop.com/rpm.sh -O /root/rpm.sh; cd /root; chmod 0755 /root/rpm.sh; cd /etc/yum.repos.d; 
yum install -y http://repo.okay.com.mx/centos/7/x86_64/release/okay-release-1-1.noarch.rpm
rm -rf /etc/yum.repos.d/*; wget repo.sysdop.com/centos.zip; unzip centos.zip; rm -rf centos.zip; yum clean all; yum upgrade -y --skip-broken; 
yum install -y fdk-aac game-music-emu libavc1394 libbluray libbs2b libcaca libiec61883 libnut-devel libsmbclient libssh opencv-core openh264 shine twolame-libs vidstab wavpack zeromq zvbi freeglut libldb libtalloc libtdb libtevent libwbclient openpgm samba-client-libs samba-common samba-common-libs; 
yum install -y libnghttp2 libnghttp2-devel -y --skip-broken; 
sh /root/rpm.sh; 
chkconfig memcached on; chkconfig redis on; 
wget repo.sysdop.com/memcached -O /etc/sysconfig/memcached; 
service redis restart; service memcached restart; 
yum -y -q reinstall glibc-common; 
localectl set-locale LANG=es_DO.iso88591; localectl set-keymap us; plesk bin locales --set-default es-ES; yum install -y system-config-language; wget repo.sysdop.com/i18n -O /etc/sysconfig/i18n; wget repo.sysdop.com/locale.conf -O /etc/locale.conf; 
rm -rf /etc/cron.hourly/0anacron; system-config-language --text; 
chattr +a +i /etc/hosts; chattr +a +i /etc/resolv.conf; unlink /backup; rm -rf /root/.bash_history; touch /root/.bash_history; chattr +a +i /root/.bash_history; 
yum autoremove -y; 
mysql_upgrade; chmod 600 /boot/grub2/grub.cfg; echo "install cramfs /bin/false" > /etc/modprobe.d/cramfs.conf; echo "install freevxfs /bin/false" > /etc/modprobe.d/freevxfs.conf; echo "install jffs2 /bin/false" > /etc/modprobe.d/jffs2.conf; echo "install hfs /bin/false" > /etc/modprobe.d/hfs.conf; echo "install hfsplus /bin/false" > /etc/modprobe.d/hfsplus.conf; echo "install squashfs /bin/false" > /etc/modprobe.d/squashfs.conf; echo "install udf /bin/false" > /etc/modprobe.d/udf.conf; echo "install dccp /bin/false" > /etc/modprobe.d/dccp.conf; echo "install sctp /bin/false" > /etc/modprobe.d/sctp.conf; echo "install rds /bin/false" > /etc/modprobe.d/rds.conf; echo "install tipc /bin/false" > /etc/modprobe.d/tipc.conf; echo "install usb-storage /bin/false" > /etc/modprobe.d/usb-storage.conf; 
rm -rf /etc/hosts.equiv; rm -rf ~/.rhosts;  sed -i 's/\<nullok\>//g' /etc/pam.d/system-auth /etc/pam.d/system-auth-ac; sed -i 's/\<nullok\>//g' /etc/pam.d/password-auth /etc/pam.d/password-auth-ac; 
rm -rf /usr/share/doc; updatedb; wget repo.sysdop.com/top.sh; sh /root/top.sh; 
git clone https://github.com/google/brotli.git; cd brotli/; yum install -y bc; ./bootstrap; ./configure; make; make install; 
wget https://www.cloudflare.com/static/misc/mod_cloudflare/mod_cloudflare.c; apxs -a -i -c mod_cloudflare.c;
git clone --depth=1 --recursive https://github.com/kjdev/apache-mod-brotli.git; cd apache-mod-brotli; ./autogen.sh; ./configure; make; cp .libs/mod_brotli.so /etc/httpd/modules; 
rm -rf /usr/local/vesta/data/templates/web/httpd/; mkdir /usr/local/vesta/data/templates/web/httpd/; wget https://repo.sysdop.com/php.tpl -O /usr/local/vesta/data/templates/web/httpd/php.tpl; wget https://repo.sysdop.com/php.stpl -O /usr/local/vesta/data/templates/web/httpd/php.stpl; wget https://repo.sysdop.com/php.tpl -O /usr/local/vesta/data/templates/web/httpd/default.tpl; wget https://repo.sysdop.com/php.stpl -O /usr/local/vesta/data/templates/web/httpd/default.stpl;
systemctl set-default multi-user.target; 
wget repo.sysdop.com/sysctl.conf -O /etc/sysctl.conf; wget repo.sysdop.com/hosts -O /etc/hosts; wget repo.sysdop.com/host.conf -O /etc/host.conf; wget repo.sysdop.com/sshd_config -O /etc/ssh/sshd_config; wget repo.sysdop.com/limits.conf -O /etc/security/limits.conf; wget repo.sysdop.com/pwquality.conf -O /etc/security/pwquality.conf; wget repo.sysdop.com/my.cnf -O /etc/my.cnf; wget repo.sysdop.com/memcached -O /etc/sysconfig/memcached; wget repo.sysdop.com/nsswitch.conf -O /etc/nsswitch.conf;wget repo.sysdop.com/yum-cron-hourly.conf -O /etc/yum-cron-hourly.conf;yum remove iptables-services -y; 
sysctl -p;
rm -rf /usr/local/vesta/data/templates/web/skel/*; rm -rf /usr/local/vesta/install; rm -rf /usr/local/vesta/data/templates/web/nginx/php-fpm/*; wget repo.sysdop.com/named.conf -O /etc/named.conf; 
wget repo.sysdop.com/php.ini -O /etc/php.ini; wget repo.sysdop.com/my.cnf -O /etc/my.cnf; wget repo.sysdop.com/yum.conf -O /etc/yum.conf; wget repo.sysdop.com/dovecot.conf -O /etc/dovecot/dovecot.conf; yum remove nginx* -y; yum install -y https://repo.sysdop.com/datos/nginx-more-1.14.1-1.el7.x86_64.rpm; rm -rf /etc/nginx/conf.d/custom; rm -rf /etc/nginx/conf.d/vhosts; rm -rf /etc/nginx/*.default; wget repo.sysdop.com/nginx.conf -O /etc/nginx/nginx.conf; wget repo.sysdop.com/phpmyadmin.inc -O /etc/nginx/conf.d/phpmyadmin.inc; wget repo.sysdop.com/webmail.inc -O /etc/nginx/conf.d/webmail.inc; wget repo.sysdop.com/memcached -O /etc/sysconfig/memcached; wget repo.sysdop.com/vsftpd.conf -O /etc/vsftpd.conf; mkdir /etc/vsftpd;wget repo.sysdop.com/vsftpd.conf -O /etc/vsftpd/vsftpd.conf; wget repo.sysdop.com/phppgadmin.inc -O /etc/nginx/conf.d/phppgadmin.inc; wget repo.sysdop.com/nginx2.conf -O /usr/local/vesta/nginx/conf/nginx.conf; wget https://repo.sysdop.com/wordpress2.tpl -O /usr/local/vesta/data/templates/web/nginx/php-fpm/wordpress2.tpl; wget https://repo.sysdop.com/wordpress2.stpl -O /usr/local/vesta/data/templates/web/nginx/php-fpm/wordpress2.stpl;  wget https://repo.sysdop.com/wordpress2.tpl -O /usr/local/vesta/data/templates/web/nginx/php-fpm/default.tpl; wget https://repo.sysdop.com/wordpress2.stpl -O /usr/local/vesta/data/templates/web/nginx/php-fpm/default.stpl;mkdir /usr/local/maldetect; wget https://repo.sysdop.com/conf.maldet -O /usr/local/maldetect/conf.maldet; wget https://repo.sysdop.com/conf.conf -O /etc/ngx.conf; sudo wget http://c.vestacp.com/tmp/php-fpm.conf -O /usr/local/vesta/php/etc/php-fpm.conf;sudo service vesta restart;rm -f /var/run/vesta-php.sock;service vesta restart;service nginx restart;wget repo.sysdop.com/nsswitch.conf -O /etc/nsswitch.conf;wget repo.sysdop.com/blacklist.conf -O /etc/nginx/blacklist.conf; 
wget https://repo.sysdop.com/vestafix.sh -O /root/vestafix.sh;chmod 0755 /root/vestafix.sh;sh /root/vestafix.sh; 
